var buildOrder = [
  {
    name: "command_center",
    tasks: [
      { taskTime:   0, taskName: "scv" }
    ]
  }
]

var exampleBuildOrder =[{name:"command_center", tasks:[{taskTime:0, taskName:"scv"}, {taskTime:17, taskName:"scv"}, {taskTime:51, taskName:"scv"}, {taskTime:68, taskName:"scv"}, {taskTime:85, taskName:"scv"}, {taskTime:102, taskName:"scv"}, {taskTime:119, taskName:"scv"}, {taskTime:136, taskName:"scv"}, {taskTime:153, taskName:"orbital"}, {taskTime:188, taskName:"scv"}, {taskTime:205, taskName:"scv"}, {taskTime:222, taskName:"scv"}, {taskTime:239, taskName:"scv"}, {taskTime:256, taskName:"scv"}, {taskTime:273, taskName:"scv"}, {taskTime:290, taskName:"scv"}, {taskTime:307, taskName:"scv"}, {taskTime:324, taskName:"scv"}, {taskTime:341, taskName:"scv"}, {taskTime:358, taskName:"scv"}, {taskTime:375, taskName:"scv"}, {taskTime:34, taskName:"scv"}]}, {name:"orbital", tasks:[{taskTime:188, taskName:"mule"}, {taskTime:276, taskName:"mule"}]}, {name:"depot", tasks:[{taskTime:55, taskName:"construction"}, {taskTime:162, taskName:"construction"}, {taskTime:258, taskName:"construction"}, {taskTime:288, taskName:"construction"}]}, {name:"barracks", tasks:[{taskTime:93, taskName:"construction"}, {taskTime:178, taskName:"tech"}, {taskTime:153, taskName:"marine"}, {taskTime:203, taskName:"marine"}, {taskTime:228, taskName:"maurader"}, {taskTime:258, taskName:"maurader"}, {taskTime:288, taskName:"maurader"}, {taskTime:318, taskName:"maurader"}, {taskTime:348, taskName:"maurader"}, {taskTime:378, taskName:"maurader"}]}, {name:"tech", tasks:[{taskTime:211, taskName:"stim"}]}, {name:"refinery", tasks:[{taskTime:110, taskName:"construction"}, {taskTime:140, taskName:"3"}]}, {name:"barracks", tasks:[{taskTime:266, taskName:"tech"}, {taskTime:206, taskName:"construction"}, {taskTime:291, taskName:"maurader"}, {taskTime:321, taskName:"maurader"}, {taskTime:351, taskName:"maurader"}, {taskTime:381, taskName:"maurader"}]}, {name:"tech", tasks:[{taskTime:291, taskName:"shells"}]}]